import { motion } from 'framer-motion';
import { FaReact, FaPython, FaAws, FaDatabase, FaCloud } from 'react-icons/fa';
import useTypingAnimation from '../hooks/useTypingAnimation';
import '../styles/hero.css';
export default function Hero() {
  const { displayText, isTyping } = useTypingAnimation(['Full Stack Developer', 'React.js Developer', 'Python & FastAPI Developer', 'AWS Cloud Enthusiast'], { typingSpeed: 65, deletingSpeed: 35, pauseDuration: 1500, startDelay: 500 });
  const icons = [<FaReact />, <FaPython />, <FaAws />, <FaDatabase />, <FaCloud />];
  return <section id="hero" className="hero"><div className="hero-container"><motion.div className="hero-content" initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><p className="hero-greeting">Hello, I’m</p><h1 className="hero-name">Sneha Shirke</h1><div className="hero-typing-container"><span className="hero-typing-text">{displayText}</span><span className={`hero-cursor ${isTyping ? 'typing' : ''}`}>|</span></div><p className="hero-description">Full Stack Developer focused on building responsive React experiences and scalable Python/FastAPI services, with practical AWS and REST API expertise.</p><div className="hero-cta"><a href="#contact" className="btn btn-primary">Hire Me</a><a href="/Sneha-Shirke-Resume.pdf" className="btn btn-secondary" download>Download Resume</a></div></motion.div><motion.div className="hero-animation" initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .2, duration: .7 }}><div className="toolkit-container"><div className="dashboard-frame"><div className="dashboard-header"><span className="dashboard-dot red"/><span className="dashboard-dot yellow"/><span className="dashboard-dot green"/></div><div className="code-lines"><span/><span/><span/><span/></div><div className="dashboard-footer">React.js · Python · FastAPI · AWS</div></div>{icons.map((icon, i) => <motion.div key={i} className={`floating-icon icon-${i}`} animate={{ y: [-7, 7, -7] }} transition={{ duration: 3 + i*.3, repeat: Infinity, ease: 'easeInOut' }}>{icon}</motion.div>)}</div></motion.div></div></section>;
}
