import { motion } from 'framer-motion';
import { FaExternalLinkAlt, FaGithub, FaBrain } from 'react-icons/fa';
import '../styles/projects.css';
const github = 'https://github.com/Shirkesneha22';
const projects = [
  { title: 'AI Resume Analyzer & Job Matcher', tag: 'NLP · Career Tech', features: ['PDF resume upload and skill extraction', 'Role-match scoring and improvement suggestions'], stack: ['React', 'FastAPI', 'Python', 'Embeddings', 'AWS S3'], challenge: 'Designed a clear scoring workflow that makes AI feedback practical for candidates.' },
  { title: 'AI Document Intelligence Platform', tag: 'RAG · Knowledge Tools', features: ['Document upload, summaries, and question answering', 'Structured insight export for faster review'], stack: ['React', 'FastAPI', 'OpenAI', 'FAISS', 'OCR'], challenge: 'Made long documents searchable through retrieval-based answers with relevant context.' },
  { title: 'AI Analytics Dashboard', tag: 'Data · Decision Support', features: ['CSV upload and interactive visual reports', 'Trend detection and AI-generated business insights'], stack: ['React', 'Python', 'FastAPI', 'PostgreSQL', 'Chart.js'], challenge: 'Turned raw business data into concise, actionable visual stories.' },
  { title: 'AI Job Search Platform', tag: 'Full Stack · Recommendations', features: ['Searchable job listings and tailored recommendations', 'Profile-based matching with resume analysis'], stack: ['React', 'Node.js', 'MongoDB', 'OpenAI', 'Framer Motion'], challenge: 'Balanced a simple user journey with personalized role recommendations.' },
];
export default function Projects() { return <section id="projects" className="section projects"><div className="projects-container"><div className="projects-header"><h2 className="section-title">Selected Projects</h2><p className="projects-subtitle">AI-focused products designed around meaningful user problems.</p></div><div className="projects-grid">{projects.map((project, i) => <motion.article className="project-card" key={project.title} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i*.08 }}><div className={`project-preview preview-${i}`}><FaBrain/><span>{project.tag}</span></div><div className="project-card-header"><h3 className="project-title">{project.title}</h3></div><div className="project-section"><h4 className="project-section-title">Features</h4><ul className="project-features">{project.features.map(f => <li key={f} className="project-feature-item">{f}</li>)}</ul></div><div className="project-section"><h4 className="project-section-title">Tech Stack</h4><div className="project-tech">{project.stack.map(t => <span key={t} className="project-tech-item">{t}</span>)}</div></div><div className="project-challenge"><strong>Challenge</strong><p>{project.challenge}</p></div><div className="project-links"><a href={github} target="_blank" rel="noreferrer" className="project-link secondary"><FaGithub/> GitHub</a><a href="#contact" className="project-link primary"><FaExternalLinkAlt/> Request Demo</a></div></motion.article>)}</div></div></section>; }
